#pragma once

namespace NinthEngine {

typedef unsigned ColorWriteTypeBit;

enum ColorWriteType : ColorWriteTypeBit {
	COLOR_WRITE_RED = 0b1,
	COLOR_WRITE_GREEN = 0b10,
	COLOR_WRITE_BLUE = 0b100,
	COLOR_WRITE_ALPHA = 0b1000,
	COLOR_WRITE_ALL = 0b1111
};

enum BlendType {
	BLEND_ZERO,
	BLEND_ONE,
	BLEND_SRC_COLOR,
	BLEND_INV_SRC_COLOR,
	BLEND_SRC_ALPHA,
	BLEND_INV_SRC_ALPHA,
	BLEND_DEST_ALPHA,
	BLEND_INV_DEST_ALPHA,
	BLEND_DEST_COLOR,
	BLEND_INV_DEST_COLOR,
	BLEND_SRC_ALPHA_SAT,
	BLEND_BLEND_FACTOR,
	BLEND_INV_BLEND_FACTOR,
	BLEND_SRC1_COLOR,
	BLEND_INV_SRC1_COLOR,
	BLEND_SRC1_ALPHA,
	BLEND_INV_SRC1_ALPHA
};

enum BlendOpType {
	BLEND_OP_ADD,
	BLEND_OP_SUBTRACT,
	BLEND_OP_REV_SUBTRACT,
	BLEND_OP_MIN,
	BLEND_OP_MAX
};

} // namespace NinthEngine