#pragma once

namespace NinthEngine {

#define FORMAT_RGBA		0b0
#define FORMAT_RGB		0b1
#define FORMAT_RG		0b10
#define FORMAT_R		0b100

#define FORMAT_8		0b0
#define FORMAT_16		0b1000
#define FORMAT_32		0b10000

#define FORMAT_UNORM	0b0
#define FORMAT_SNORM	0b100000
#define FORMAT_UINT		0b1000000
#define FORMAT_SINT		0b10000000
#define FORMAT_FLOAT	0b100000000

#define FORMAT_DEPTH	0b1000000000

enum FormatType : unsigned {
	FORMAT_RGBA_8_UNORM	= FORMAT_RGBA | FORMAT_8 | FORMAT_UNORM,
	FORMAT_RGB_8_UNORM = FORMAT_RGB | FORMAT_8 | FORMAT_UNORM,
	FORMAT_RG_8_UNORM = FORMAT_RG | FORMAT_8 | FORMAT_UNORM,
	FORMAT_R_8_UNORM = FORMAT_R | FORMAT_8 | FORMAT_UNORM,

	FORMAT_RGBA_16_UNORM = FORMAT_RGBA | FORMAT_16 | FORMAT_UNORM,
	FORMAT_RGB_16_UNORM = FORMAT_RGB | FORMAT_16 | FORMAT_UNORM,
	FORMAT_RG_16_UNORM = FORMAT_RG | FORMAT_16 | FORMAT_UNORM,
	FORMAT_R_16_UNORM = FORMAT_R | FORMAT_16 | FORMAT_UNORM,

	FORMAT_RGBA_8_SNORM = FORMAT_RGBA | FORMAT_8 | FORMAT_SNORM,
	FORMAT_RGB_8_SNORM = FORMAT_RGB | FORMAT_8 | FORMAT_SNORM,
	FORMAT_RG_8_SNORM = FORMAT_RG | FORMAT_8 | FORMAT_SNORM,
	FORMAT_R_8_SNORM = FORMAT_R | FORMAT_8 | FORMAT_SNORM,

	FORMAT_RGBA_16_SNORM = FORMAT_RGBA | FORMAT_16 | FORMAT_SNORM,
	FORMAT_RGB_16_SNORM = FORMAT_RGB | FORMAT_16 | FORMAT_SNORM,
	FORMAT_RG_16_SNORM = FORMAT_RG | FORMAT_16 | FORMAT_SNORM,
	FORMAT_R_16_SNORM = FORMAT_R | FORMAT_16 | FORMAT_SNORM,

	FORMAT_RGBA_8_UINT = FORMAT_RGBA | FORMAT_8 | FORMAT_UINT,
	FORMAT_RGB_8_UINT = FORMAT_RGB | FORMAT_8 | FORMAT_UINT,
	FORMAT_RG_8_UINT = FORMAT_RG | FORMAT_8 | FORMAT_UINT,
	FORMAT_R_8_UINT = FORMAT_R | FORMAT_8 | FORMAT_UINT,

	FORMAT_RGBA_16_UINT = FORMAT_RGBA | FORMAT_16 | FORMAT_UINT,
	FORMAT_RGB_16_UINT = FORMAT_RGB | FORMAT_16 | FORMAT_UINT,
	FORMAT_RG_16_UINT = FORMAT_RG | FORMAT_16 | FORMAT_UINT,
	FORMAT_R_16_UINT = FORMAT_R | FORMAT_16 | FORMAT_UINT,

	FORMAT_RGBA_32_UINT = FORMAT_RGBA | FORMAT_32 | FORMAT_UINT,
	FORMAT_RGB_32_UINT = FORMAT_RGB | FORMAT_32 | FORMAT_UINT,
	FORMAT_RG_32_UINT = FORMAT_RG | FORMAT_32 | FORMAT_UINT,
	FORMAT_R_32_UINT = FORMAT_R | FORMAT_32 | FORMAT_UINT,

	FORMAT_RGBA_8_SINT = FORMAT_RGBA | FORMAT_8 | FORMAT_SINT,
	FORMAT_RGB_8_SINT = FORMAT_RGB | FORMAT_8 | FORMAT_SINT,
	FORMAT_RG_8_SINT = FORMAT_RG | FORMAT_8 | FORMAT_SINT,
	FORMAT_R_8_SINT = FORMAT_R | FORMAT_8 | FORMAT_SINT,

	FORMAT_RGBA_16_SINT = FORMAT_RGBA | FORMAT_16 | FORMAT_SINT,
	FORMAT_RGB_16_SINT = FORMAT_RGB | FORMAT_16 | FORMAT_SINT,
	FORMAT_RG_16_SINT = FORMAT_RG | FORMAT_16 | FORMAT_SINT,
	FORMAT_R_16_SINT = FORMAT_R | FORMAT_16 | FORMAT_SINT,

	FORMAT_RGBA_32_SINT = FORMAT_RGBA | FORMAT_32 | FORMAT_SINT,
	FORMAT_RGB_32_SINT = FORMAT_RGB | FORMAT_32 | FORMAT_SINT,
	FORMAT_RG_32_SINT = FORMAT_RG | FORMAT_32 | FORMAT_SINT,
	FORMAT_R_32_SINT = FORMAT_R | FORMAT_32 | FORMAT_SINT,

	FORMAT_RGBA_16_FLOAT = FORMAT_RGBA | FORMAT_16 | FORMAT_FLOAT,
	FORMAT_RGB_16_FLOAT = FORMAT_RGB | FORMAT_16 | FORMAT_FLOAT,
	FORMAT_RG_16_FLOAT = FORMAT_RG | FORMAT_16 | FORMAT_FLOAT,
	FORMAT_R_16_FLOAT = FORMAT_R | FORMAT_16 | FORMAT_FLOAT,

	FORMAT_RGBA_32_FLOAT = FORMAT_RGBA | FORMAT_32 | FORMAT_FLOAT,
	FORMAT_RGB_32_FLOAT = FORMAT_RGB | FORMAT_32 | FORMAT_FLOAT,
	FORMAT_RG_32_FLOAT = FORMAT_RG | FORMAT_32 | FORMAT_FLOAT,
	FORMAT_R_32_FLOAT = FORMAT_R | FORMAT_32 | FORMAT_FLOAT,

	FORMAT_DEPTH_16 = FORMAT_DEPTH,
	FORMAT_DEPTH_32,
	FORMAT_DEPTH_32F,
	FORMAT_DEPTH_24_STENCIL_8,
	FORMAT_DEPTH_32F_STENCIL_8
};

} // namespace NinthEngine